platform:ios,'7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'SBJson', '~> 4.0.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 2.3.2'
pod 'FMDB', '~> 2.5'
pod 'Reachability', '~> 3.2'
pod 'UMengSocial', '~> 4.2.3'
